---
- name: HTTPD 설치
  hosts: koreaeast
  gather_facts: true
  become: yes

  tasks:
    - name: httpd installation
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: apache2 ubuntu install
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
