---
- name: server setting
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: make nfs_shared forder
      file:
        path: /home/vagrant/shared
        state: directory
        mode: 0777

    - name: /etc/export setting
      lineinfile:
        path: /etc/exports
        line: /home/vagrant/shared 10.10.10.0/24(rw,sync)

    - name: nfs serveice restart
      become: yes
      service:
        name: nfs
        state: restarted

    - name: create test file
      file:
        path: /home/vagrant/shared/test
        state: touch

    - name: /etc/export test file createing
      lineinfile:
        path: /home/vagrant/shared/test
        line: "{{ item }}"
      with_items:
        - "guildong"
        - "chulsoo"
        - "minsoo"

- name: nfs client setting
  hosts: all
  gather_facts: no

  tasks:
    - name: /home/vagrant/remote create directory
      file:
        path: /home/vagrant/remote
        state: directory

    - name: mount point directory as client
      become: yes
      mount:
        path: /home/vagrant/remote
        src: 10.10.10.10:/home/vagrant/shared
        fstype: nfs
        opts: nfsvers=3
        state: mounted

    - name: print nfs forler
      shell: "cat /home/vagrant/remote/test"
