# -*- mode: ruby -*-
# vi: set ft=ruby :

## configuration variables ##
# max number of worker nodes
C_NODE_MAX_SEQ = 3
U_NODE_MAX_SEQ = 5

Vagrant.configure("2") do |config|
  # Create W-Node
  (1..C_NODE_MAX_SEQ).each do |i|
    config.vm.define "ansible-node0#{i}" do |cfg|
      cfg.vm.box = "centos/7"
      cfg.vm.host_name = "ansible-node0#{i}"
      cfg.vm.network "public_network", :dev => "br0", :mode => "bridge",  :type =>"bridge"
      cfg.vm.network "private_network", ip: "10.10.10.1#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6001#{i}", auto_correct: true, id: "ssh"
      cfg.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/mykey.pem.pub"
      cfg.vm.provision "shell", inline: "cat /home/vagrant/.ssh/mykey.pem.pub >> /home/vagrant/.ssh/authorized_keys"
    end
  end

  (C_NODE_MAX_SEQ+1..U_NODE_MAX_SEQ).each do |i|
    config.vm.define "ansible-node0#{i}" do |cfg|
      cfg.vm.box = "generic/ubuntu1804"
      cfg.vm.host_name = "ansible-node0#{i}"
      cfg.vm.network "public_network", :dev => "br0", :mode => "bridge",  :type =>"bridge"
      cfg.vm.network "private_network", ip: "10.10.10.1#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6001#{i}", auto_correct: true, id: "ssh"
      cfg.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/mykey.pem.pub"
      cfg.vm.provision "shell", inline: "cat /home/vagrant/.ssh/mykey.pem.pub >> /home/vagrant/.ssh/authorized_keys"
    end
  end

  # Master
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.host_name = "ansible-server"
    cfg.vm.provider "libvirt" do |res|
      res.cpus = 2
      res.memory = 1024
    end
    cfg.vm.network "public_network", :dev => "br0", :mode => "bridge",  :type =>"bridge"
    cfg.vm.network "private_network", ip: "10.10.10.10"
    cfg.vm.network "forwarded_port", guest: 22, host: "60010", auto_correct: true, id: "ssh"
    cfg.vm.provision "shell", inline: "yum install -y epel-release"
    cfg.vm.provision "shell", inline: "yum install -y ansible"
    cfg.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
    cfg.vm.provision "shell", inline: "chmod 600 /home/vagrant/.ssh/id_rsa"
    cfg.vm.provision "shell", inline: "echo '10.10.10.11' >> /etc/ansible/hosts"
    cfg.vm.provision "shell", inline: "echo '10.10.10.12' >> /etc/ansible/hosts"
    cfg.vm.provision "shell", inline: "echo '10.10.10.13' >> /etc/ansible/hosts"
    cfg.vm.provision "shell", inline: "echo '10.10.10.14' >> /etc/ansible/hosts"
    cfg.vm.provision "shell", inline: "echo '10.10.10.15' >> /etc/ansible/hosts"
    cfg.vm.provision "shell", inline: "ssh-keyscan 10.10.10.11 >> /home/vagrant/.ssh/known_hosts"
    cfg.vm.provision "shell", inline: "ssh-keyscan 10.10.10.12 >> /home/vagrant/.ssh/known_hosts"
    cfg.vm.provision "shell", inline: "ssh-keyscan 10.10.10.13 >> /home/vagrant/.ssh/known_hosts"
    cfg.vm.provision "shell", inline: "ssh-keyscan 10.10.10.14 >> /home/vagrant/.ssh/known_hosts"
    cfg.vm.provision "shell", inline: "ssh-keyscan 10.10.10.15 >> /home/vagrant/.ssh/known_hosts"
    cfg.vm.provision "shell", inline: "chown vagrant.vagrant /home/vagrant/.ssh/known_hosts"
  end
end
